#!/usr/bin/with-contenv sh

CONFIG_FILE=/config/config.xml

# create initial config file
if [[ ! -f "$CONFIG_FILE" ]]; then
  TMP_FILE="$(mktemp)"
  cat <<EOF >"$TMP_FILE"
<Config>
  <AnalyticsEnabled>False</AnalyticsEnabled>
</Config>
EOF

  install -m644 -o $PUID -g $PGID "$TMP_FILE" "$CONFIG_FILE"
fi

# change chdir
cd /config

# delete pid before start
rm -f sonarr.pid

# run with limited permissions
exec s6-setuidgid $PUID:$PGID /app/bin/Sonarr -nobrowser -data=/config
